### ISSUE TITLE
Add support for enums to addOption()

### ISSUE THREAD

**Issue by martinsik** [dart-lang/args#11]
I think it would be nice to be able to use enums from Dart 1.9 as parameters to `addOption()`'s allowed values. Something like this:
```dart
enum Commands { start, stop, status }
addOption('cmd', abbr: 'c', allowed: Commands)
```

**Comment by nex3** [comment]
I don't think there's any way to get a list of values out of an enum's `Type` other than using `dart:mirrors`, which isn't a good option for a cross-platform package like `args`.

**Comment by seaneagan** [comment]
This is close to the top of the list of features I want to add to unscripted:

https://github.com/seaneagan/unscripted/issues/13

Patches welcome!

**Comment by eernstg** [comment]
Hi Martin,

if you have a specific enum in mind, couldn't you get much of what you want
using the following (not tested, it just illustrates the idea):

  List<String> listToStringList(List xs) => xs.map((value) =>
value.toString()).toList();

  addOption('cmd', abbr: 'c', allowed: listToStringList(Commands.values));

It's a workaround, but not a huge one..

On Mon, Apr 27, 2015 at 8:01 PM, Natalie Weizenbaum <
notifications@github.com> wrote:

> I don't think there's any way to get a list of values out of an enum's
> Type other than using dart:mirrors, which isn't a good option for a
> cross-platform package like args.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/args/issues/11#issuecomment-96761381>.
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by seaneagan** [comment]
That still doesn't address adding help text for each option.  Of course you could have a separate `Map<Commands, String>` which stores that, but that's not as DRY as just annotating the enum members.  And of course enums ought to be able to have their own fields, but then it still wouldn't be generic, unless there were some `HelpText` or similar interface that enums could implement.

**Comment by eernstg** [comment]
With the proposed metaclasses for Dart (see
https://github.com/gbracha/metaclasses), the expression `Commands` would
evaluate to an object of type Type which represents the class Commands, and
it would respond to `values` just like the static method `values` on any
enum class.

This means that we could get the values of a given enum class and transform
each value into a String in a generic manner (with no static knowledge of
the exact enum class, just relying on the given instance of Type
representing that enum class) without any use of dart:mirrors. An
accompanying argument of type Map<Object, String> or `String
helpMapper(Object enumValue)` could then provide the help strings. The
typing is loose (we can't say that the arguments to a helpMapper must be a
value of the given enum class), but it would work, and it would be generic.

If it is considered worthwhile, that generic code could then sit in the
implementation of `addOption`, and it could take extra arguments similar to
the following:

  addOption(... {... allowedEnum: Type, allowedEnumHelp: Map<Object,
String>});

Otherwise it wouldn't be hard to write a helper function that receives
these arguments and calls addOption after having transformed the enum type
to a List<Strings> for `allowed`, and the `allowedEnumHelp` mapping into a
suitable argument for `allowedHelp`.

In any case, this would be blocked until we have those metaclasses.


On Mon, Apr 27, 2015 at 9:06 PM, Sean Eagan <notifications@github.com>
wrote:

> That still doesn't address adding help text for each option. Of course you
> could have a separate Map<Commands, String> which stores that, but that's
> not as DRY as just annotating the enum members. And of course enums ought
> to be able to have their own fields, but then it still wouldn't be generic,
> unless there were some HelpText or similar interface that enums could
> implement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/args/issues/11#issuecomment-96782333>.
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by martinsik** [comment]
I didn't know there could be a problem with `dart:mirrors` but something like this is better than nothing:

```dart
addOption('cmd', abbr: 'c', allowed: Commands.values)
```
Which can be easily converted to allowed string values:

```dart
values.map((val) => val.toString().split('.')[1]);
```

Then converting string arguments back to enums could work similarly.

**Comment by nex3** [comment]
I don't think that's substantially simpler than manually converting values to strings, and since it isn't typable it would be a lot harder to comprehend.
