### ISSUE TITLE
ArgParser addOption method allowed property

### ISSUE THREAD

**Issue by dev-aentgs** [dart-lang/args#144]
On [pub.dev readme](https://pub.dev/packages/args), the part explaining usage of `allowed:` property mentions its value to be `set` but in example `list` is given.

> To validate a non-flag option, you can use the allowed parameter to provide an allowed set of values. When you do, the parser throws an ArgParserException if the value for an option is not in the allowed set. Here's an example of specifying allowed values:
`parser.addOption('mode', allowed: ['debug', 'release']);`
>
On the [addOption documentation page](https://pub.dev/documentation/args/latest/args/ArgParser/addOption.html) , the implementation is using `Iterable<String> allowed` . 
So it can take `set` or `list` as values to the `allowed:` property.

Are there any cases where the `allowed:` would benefit by having repeated values in the `list` ?
If only unique values are going to be the input, it would be more reasonable to explicitly use a `set` there instead of `list`.

**Comment by jakemac53** [comment]
It is pretty common practice to accept an `Iterable` where you want a collection of things. It is more flexible/ergonomic because it doesn't require users to copy their list/iterable/etc into a Set.

This api is also not broken by a user passing a collection that contains repeated values, so there isn't really any harm in accepting collections that may contain duplicates.

It is conceptually a `set` though, in that duplicates have no value, which is why the docs use that word.

Note that it would also be a breaking change for this package to change it to a `Set`, and this is a very widely used package so the bar for something breaking is set very high.
