### ISSUE TITLE
Non-zero exit code after printing command usage

### ISSUE THREAD

**Issue by asashour** [dart-lang/args#205]
Initiated in https://github.com/flutter/flutter/issues/5797

When a program prints the usage, it usually returns non-zero, e.g. `git` and `help`.

**Comment by jakemac53** [comment]
In general, this package does not set exit codes, it only deals with arg parsing. Usually you would set it in your own command implementations, or possibly catch some exceptions that you throw outside of that and then set exit codes.

The help command specifically is a bit weird in this case though... because it is built in. According to [the docs](https://github.com/dart-lang/args/blob/master/README.md#default-help-command) it throws a `UsageException` which you could catch and set an exit code, but I am not sure that the docs are actually up to date, I don't see us throwing that exception today (and doing so would be a breaking change, which is likely not justified by this).

**Comment by devoncarew** [comment]
I agree - this is out of scope for package:args.
