### ISSUE TITLE
Text after a newline in a Command's description is not displayed

### ISSUE THREAD

**Issue by sethladd** [dart-lang/args#42]
Here's a repro:

```
import 'package:args/args.dart';
import 'package:args/command_runner.dart';

class FooCommand extends Command {
  String get name => 'foo';
  String get description => 'This is a \ntest';

  run() {}
}

main(args) {
  var runner = new CommandRunner('y', 'z');
  runner.addCommand(new FooCommand());

  print(runner.usage);
}
```

Expected:

```
Available commands:
  foo    This is a
           test.
  help   Display help information for y.
```

Actual:

```
Available commands:
  foo    This is a 
  help   Display help information for y.
```

**Comment by sethladd** [comment]
Motivation: we have a very long description for one of our commands. It doesn't wrap cleanly, so I wanted to insert newlines at the 80 char mark.

Related: https://github.com/flutter/flutter/issues/1225

**Comment by sethladd** [comment]
Thanks!

**Comment by nex3** [comment]
Since making this change, I've realized that pub actually relied on the old behavior to display only a brief summary of a command in the initial `pub help` documentation, while displaying a longer description in the `pub help command` documentation.

I'm going to revert this back to the old behavior by default, but I'll also add a way to override it. I'll add a `Command.shortDescription` getter that's used in the parent command's usage string, which defaults to the first line of `Command.description` but can be overridden.
