### ISSUE TITLE
Add a merge method to ArgResults

### ISSUE THREAD

**Issue by srawlins** [dart-lang/args#61]
There are cases where args might be supplied in two different places, and then we want to merge them. For example, `myscript.dart` might allow args to be passed in via the cmdline, and defaults may also be supplied in `~/.myscriptrc`.

I would expect ArgResults.merge to basically behave the same as [Map.addAll](https://api.dartlang.org/stable/1.21.0/dart-core/Map/addAll.html). Specifically, given `resultsFromRc.merge(resultsFromCmdline)`, each arg in `resultsFromCmdline` that `wasParsed` is added to `resultsFromRc`, overwriting any existing values.

It is hard for a user to merge each `List<String>` before parsing them, and it's hard to implement this feature as a user since ArgResults does not expose a Map of all arguments that were parsed, or that exist with their default values.

**Comment by nex3** [comment]
There are a lot of details with the merging API you're proposing that seem tricky in practice. What happens if the results are from different parsers? What if they both have positional parameters? What if they select different commands? What if the parser relies on callbacks rather than after-the-fact parsing? These aren't necessarily insurmountable, but the fact that the answer is non-obvious makes me wonder if merging `ArgResult`s after the fact is the best way to represent this idea.

In `test`, we support this by having a separate `Configuration` class that can be populated using args or by loading from a file. This gives us more flexibility in terms of the configuration file, where CLI flags aren't necessarily the best UI for setting options (`test` uses YAML instead) and where not all options configurable via CLI make sense. It also gives us a well-typed way of accessing the configuration, and finer-grained control over exactly how options are merged between different sources.

> It is hard for a user to merge each `List<String>` before parsing them

Can you go into more detail about why this is difficult?

**Comment by srawlins** [comment]
Merging the `List<String>`s manually before parsing them with ArgParser is hard because you have to parse them anyways. You might have flag `--force` with a short value `-f`, and then you might have `--force` on the cmdline and `-f` from another source, and you're just re-writing the package:args parser.

I'd be happy with the following constraints on such a merge (which could be relaxed later if demand arises):

* Must come from same ArgParser
* Must not include positional parameters, or maybe just that `other`'s values overwrite `this`'s values.
* Maybe different commands don't matter?
* Callbacks might be tricky... On the face of it, they're just not run again? Probably not a good idea to use callbacks if you're going to merge?

**Comment by nex3** [comment]
> Merging the `List<String>`s manually before parsing them with ArgParser is hard because you have to parse them anyways. You might have flag `--force` with a short value `-f`, and then you might have `--force` on the cmdline and `-f` from another source, and you're just re-writing the package:args parser.

Can't you just concatenate the lists? `args` can handle multiple instances of the same argument; it'll just overwrite the value if necessary.

**Comment by natebosch** [comment]
@srawlins has this come up again since you filed the request?

I do think that concatenating the args should work in the limited cases we are likely to be able to support here, and that for more complicated cases you'd need to handle conflicts and everything with application specific logic.

**Comment by srawlins** [comment]
I don't think so. I'm not certain which project triggered this request, 4 years ago :/

**Comment by natebosch** [comment]
Closing for now until we find a current use case.
