### ISSUE TITLE
Export Parser class

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/args#74]
Is there any chance of adding [`Parser`](https://github.com/dart-lang/args/blob/master/lib/src/parser.dart#L18) to the exports for this package? I've implemented a "lenient" arg parser in a separate project that ignores unexpected args (see https://github.com/dart-lang/args/issues/9) and did so by extending `Parser`. I think this class provides value on its own, but understand if it's not something that you'd want to commit to as a part of the public API.

**Comment by nex3** [comment]
I don't think it's worth expanding the surface area of this API that much just to hypothetically allow users to customize the behavior in ways we haven't predicted. Keeping the parser private makes it much safer for us to evolve the existing APIs, since we can make backwards-incompatible changes to the internal API without breaking downstream users.
