### ISSUE TITLE
CommandRunner.runCommand NPE...

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/args#81]
... if you override `usageException`.

I want to log usage exceptions, not `throw`, so I overrode `usageException`:

```dart
@override
usageException(message) => log(message);
```

Unfortunately, this runs into a bad branch in `runCommand`:

```dart
if (command == null) {
  usageException('Could not find a command named "${argResults.rest[0]}".');
}

command.usageException('Could not find a subcommand named '
  '"${argResults.rest[0]}" for "$commandString".');
```

I believe the right behavior would be:

```dart
if (command == null) {
  usageException( 'Could not find a command named "${argResults.rest[0]}".');
} else {
  command.usageException('Could not find a subcommand named '
    '"${argResults.rest[0]}" for "$commandString".');
}
```

Happy to send a tiny PR.

**Comment by nex3** [comment]
The documentation for `usageException()` says

> Throws a `UsageException` with `message`.

By overriding it with a logging function, you're violating the contract that the caller expects, which will generally cause unexpected and broken behavior.

Can I ask what your goal is with this override? Why not just use a `try`/`catch` to handle a `UsageException`?

**Comment by matanlurey** [comment]
Other than the fact the Dart style guide says _not_ to use exception throwing for behavior, it seems to be pretty straightforward to add that `else` block. Basically, I have a "bot" interface (think for Allo, Discord, Slack) that accepts commands using pkg/args.

For a one-off command, i.e.

`dart bin/bot.dart say hello`

It's fine to throw if the command is missing.

For a persistent bot, I want to give the message to the client and play nice:

`> I don't understand "say", did you mean "see"?`

**Comment by nex3** [comment]
> Other than the fact the Dart style guide says _not_ to use exception throwing for behavior

I can't find this in the style guide... I've seen other languages' style guides advocate avoiding exceptions for *control flow*, but catching an exception that indicates invalid input seems totally reasonable to me. That's how all code that uses `FormatException`s works, for example.

> it seems to be pretty straightforward to add that `else` block.

It's more than just one `else` block. We'd have to be careful to ensure that every call to `usageException()` that exists now and in the future doesn't assume it will throw, and that it has coherent and documented behavior if it doesn't. You could even make the case that it's a breaking API change, since `CommandRunner.usageException()` is public and could theoretically be called by third-party code that takes a foreign `CommandRunner` object (although it's unlikely that such code exists in practice).

> Basically, I have a "bot" interface (think for Allo, Discord, Slack) that accepts commands using pkg/args.

I don't understand why catching the error doesn't work in this case.

**Comment by natebosch** [comment]
`usageException` now has a static return type of `Never`, which means that if you override it it won't allow you to not throw. It doesn't address the request precisely, but it does give you some static help and removes the footgun.

I think what you can do is add a `try/catch` at a higher level.

```dart
try {
  await commandRunner.run(args);
} on UsageException catch(e) {
  log(e.message);
}
```
